### ISSUE TITLE
Old version of kotlinx.serialization?

### ISSUE THREAD

**Issue by RubixDev** [JesseCorbett/Diskord#12]
I wanted to use the json serialization and deserialization of kotlinx to store data in json files, but Diskord seems to already have an older version of it as a dependency. With Diskord as a dependency removed the json deserialization works with no problems, but with it as a dependency I get an error during building, that `kotlinx.serialization.decodeFromString` is an `unresolved reference`.

This is my current `build.gradle.kts`:
```kts
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.4.32"
    kotlin("plugin.serialization") version "1.4.32"
}

group = "de.rubixdev"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation("com.jessecorbett:diskord:1.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.1.0")
    testImplementation(kotlin("test-junit"))
}

tasks.test {
    useJUnit()
}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "13"
}
```

If any more information is needed, feel free to ask.

**Comment by JesseCorbett** [comment]
The outdated dependency is a known concern, we plan on releasing a vastly updated version of Diskord soon which will update all the dependencies among other things

**Comment by RubixDev** [comment]
Can I already use any pre release version until then?

**Comment by JesseCorbett** [comment]
Yes, you can use the current snapshot version (2.0.0-SNAPSHOT) by following the instructions at the bottom of the README. There may be some minor compatibility issues (we haven't finished documentation for the new version) but nothing too complicated.

If you have further questions feel free to ask or visit the discord group
