### ISSUE TITLE
`rgb` function in Colors.kt translates float colours incorrectly.

### ISSUE THREAD

**Issue by solonovamax** [JesseCorbett/Diskord#14]
The [`rgb`](https://github.com/JesseCorbett/Diskord/blob/master/diskord-core/src/commonMain/kotlin/com/jessecorbett/diskord/util/Colors.kt#L161-L167) function in [`Colors.kt`](https://github.com/JesseCorbett/Diskord/blob/master/diskord-core/src/commonMain/kotlin/com/jessecorbett/diskord/util/Colors.kt) translates float colours incorrectly.
If provided with the float `0.999`, it will compute the RGB color to be 254. This is incorrect. As a float it is computed to be 254.745, which should be rounded to 255, not 254.

This happens because the `toInt` function does not round and just truncates the decimal.

Either use
```kotlin
fun rgb(red: Double, green: Double, blue: Double): Color {
    require(red in 0.0F..1.0F) { "$red is not between 0 and 1." }
    require(green in 0.0F..1.0F) { "$green is not between 0 and 1." }
    require(blue in 0.0F..1.0F) { "$blue is not between 0 and 1." }

    return rgb((red * 255).roundToInt(), (green * 255).roundToInt(), (blue * 255).roundToInt())
}
```
or
```kotlin
fun rgb(red: Double, green: Double, blue: Double): Color {
    require(red in 0.0F..1.0F) { "$red is not between 0 and 1." }
    require(green in 0.0F..1.0F) { "$green is not between 0 and 1." }
    require(blue in 0.0F..1.0F) { "$blue is not between 0 and 1." }

    return rgb((red * 255 + 0.5).toInt(), (green * 255 + 0.5).toInt(), (blue * 255 + 0.5).toInt())
}
```
to fix this.

**Comment by solonovamax** [comment]
When the `red` value is set to 99.9 with GIMP:

![image](https://user-images.githubusercontent.com/46940694/147779649-117be1b5-eeaa-4f3b-9cd9-c04fc9bb0c5f.png)

**Comment by syorito-hatsuki** [comment]
refactor and send pull request

**Comment by solonovamax** [comment]
I just realized this is a mirror of the diskord gitlab repo, so I'll open an issue and pr there.

**Comment by JesseCorbett** [comment]
Thanks for the ticket, has been resolved upstream and will be released soon
