### ISSUE TITLE
The README must specify the `jcenter()` repository in the gradle setup, to be able to download Kotlinx.serialization

### ISSUE THREAD

**Issue by natanfudge** [JesseCorbett/Diskord#4]
This project depends on [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) which is only available on the `jcenter()` repository. Without this specified in the `repositories` block, the project will fail to build.
Simply add this to the readme:
```
repositories {
    mavenCentral()
    jcenter()
}
```

**Comment by JesseCorbett** [comment]
This has been added
