### ISSUE TITLE
SLF4J warning when starting bot

### ISSUE THREAD

**Issue by natanfudge** [JesseCorbett/Diskord#5]
I get this concerning warning in red when starting the bot:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by JesseCorbett** [comment]
The warning is a non-issue. It's a symptom of Diskord using the standard slf4j logging library, which expects a logging implementation, such as logback, to pipe logging to. This can be safely ignored if you don't want to bother with setting up a logging library though, and we'll consider how this experience might be improved for people not experienced with slf4j
