### ISSUE TITLE
Gateway Intents

### ISSUE THREAD

**Issue by gdude2002** [JesseCorbett/Diskord#8]
With the way Discord is attempting to address various privacy issues, implementing gateway intents [as per the documentation](https://discordapp.com/developers/docs/topics/gateway#privileged-intents) really is a must.

It should be relatively simple to support, especially considering Diskord doesn't appear to do any caching (at least as far as a cursory search goes).

**Comment by JesseCorbett** [comment]
Just want to update this ticket so it's documented in GitHub that this is on the roadmap for me, and should be available in a future release

**Comment by incendium** [comment]
Addressed in https://gitlab.com/jesselcorbett/diskord/-/issues/25.
