### ISSUE TITLE
Calling Message Extention functions outside of bot context

### ISSUE THREAD

**Issue by mckernant1** [JesseCorbett/Diskord#9]
Hi, I really enjoy this library, but I'm finding it hard to separate this into different readable files/functions

For example I am trying to pass the message from the schedule command out to another function, but the react extension function is not declared outside of the bot block

```kotlin
suspend fun main() {
    bot(BOT_TOKEN) {
        commands("!") {
            command("schedule") {
               schedule(this)
            }
        }
        suspend fun react(m: Message) {
            m.react("⛔") // This is allowed
        }
    }
}

fun schedule(m: Message) {
    m.react("⛔") // This is not allowed because the react extension function is only declared within the bot block
}
```

I was wondering if you had a suggestion/example for breaking up a bot into multiple files or functions
Thanks!

**Comment by JesseCorbett** [comment]
Hey @mckernant1 and thanks for the ticket. You can modify your function by changing the definition from `fun schedule(m: Message)` to `fun Bot.schedule(m: Message)`

**Comment by mckernant1** [comment]
Ahhh i see. Thanks!
